include: package:very_good_analysis/analysis_options.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "build/**"

linter:
  rules:
    # Ajustes opcionais (mantém bem “take-home friendly”)
    public_member_api_docs: false
